# Generated by Django 4.1.3 on 2022-11-28 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_survey_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 12, 6, 55, 276052)),
        ),
    ]
