# Generated by Django 4.1.3 on 2022-11-14 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_survey_deadline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngerAnswer',
            new_name='IntegerAnswer',
        ),
        migrations.AlterField(
            model_name='survey',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 9, 17, 31, 699593)),
        ),
    ]
