# Generated by Django 4.1.3 on 2022-11-29 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_alter_survey_deadline_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 9, 18, 52, 788749)),
        ),
    ]
