# Generated by Django 4.1.3 on 2022-11-17 13:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_alter_survey_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='submition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submition_answers', to='survey.submition'),
        ),
        migrations.AlterField(
            model_name='integeranswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integer_answers', to='survey.answer'),
        ),
        migrations.AlterField(
            model_name='optionanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_answers', to='survey.answer'),
        ),
        migrations.AlterField(
            model_name='optionanswer',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_options_in_answer', to='survey.questionoption'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='survey.question'),
        ),
        migrations.AlterField(
            model_name='submition',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitions', to='survey.survey'),
        ),
        migrations.AlterField(
            model_name='submition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_submitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 9, 59, 42, 419083)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='textanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_answers', to='survey.answer'),
        ),
    ]
