# Generated by Django 4.1.3 on 2022-11-17 15:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_alter_answer_question_alter_answer_submition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integeranswer',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integer_answers', to='survey.answer'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 11, 57, 49, 782966)),
        ),
        migrations.AlterField(
            model_name='textanswer',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_answers', to='survey.answer'),
        ),
    ]
