# Generated by Django 4.1.3 on 2022-11-18 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_alter_integeranswer_answer_alter_survey_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 10, 6, 24, 797480)),
        ),
    ]
