# Generated by Django 4.1.3 on 2022-11-22 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_alter_survey_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='survey',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 10, 46, 59, 613346)),
        ),
    ]
